env:
  browser: true
  es2020: true
extends: google
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  no-invalid-this: off
  prefer-rest-params: off
  no-unused-vars: off
  require-jsdoc: off
  indent: off
  camelcase:
    - 2
    - allow: ['^(am4|client_id)']

