env:
  browser: true
  es2020: true
extends: google
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  no-unused-vars: off
  require-jsdoc: off
  indent: [
    "error", 2,  # Google use 2-space indents
    # Google uses +4 space indents for line continuations.
    {
        "SwitchCase": 1,
        "MemberExpression": "off"
        "FunctionDeclaration": {
            "body": 1,
            "parameters": "off"
        },
        "FunctionExpression": {
            "body": "off",
            "parameters": 2
        },
        "CallExpression": {
            "arguments": "off"
        },
        # Ignore default rules for ternary expressions.
        "ignoredNodes": ["ConditionalExpression"]
    }
  ]
