env:
  browser: true
  es2020: true
extends: google
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  no-unused-vars: off
  require-jsdoc: off
  indent: [
    "error", 2,
    {
        "SwitchCase": 1,
        "MemberExpression": 0,
        "FunctionDeclaration": {
            "body": 1,
            "parameters": 0
        },
        "FunctionExpression": {
            "body": 0,
            "parameters": 2
        },
        "CallExpression": {
            "arguments": 0
        },
        # Ignore default rules for ternary expressions.
        "ignoredNodes": ["ConditionalExpression"]
    }
  ]
